definitions:
  consume.AddConsumeRequest:
    properties:
      money:
        type: number
      remark:
        type: string
      type:
        type: integer
    type: object
  consume.AddConsumeTypeReq:
    properties:
      type_name:
        type: string
    type: object
  consume.DelConsumeTypeReq:
    properties:
      id:
        type: integer
    type: object
  consume.UpdateConsumeRequest:
    properties:
      id:
        type: integer
      money:
        type: number
      remark:
        type: string
      type:
        type: integer
    type: object
  user.LoginRequest:
    properties:
      password:
        type: string
      user_name:
        type: string
    required:
    - password
    - user_name
    type: object
  user.Register:
    properties:
      code:
        type: integer
      email:
        type: string
      icon:
        type: string
      password:
        type: string
      user_name:
        type: string
    required:
    - code
    - password
    - user_name
    type: object
  user.Verify:
    properties:
      code:
        type: string
      id:
        type: string
    required:
    - code
    - id
    type: object
  webbase.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact:
    email: zzzzzz1916@qq.com
    name: API Support
  termsOfService: https://github.com/yangjunyangjun/ledger
  title: Golang ledger API
  version: "1.0"
paths:
  /ledger/v1/consume/add_consume:
    post:
      description: 新增消费记录
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: JSON数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/consume.AddConsumeRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 消费管理相关接口
  /ledger/v1/consume/add_consume_type:
    post:
      description: 新增消费种类
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: JSON数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/consume.AddConsumeTypeReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 消费管理相关接口
  /ledger/v1/consume/consume_list:
    get:
      description: 消费记录列表
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - in: query
        name: end_time
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      - in: query
        name: start_time
        type: string
      - in: query
        name: type
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 消费管理相关接口
  /ledger/v1/consume/consume_type_list:
    get:
      description: 消费种类列表
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 消费管理相关接口
  /ledger/v1/consume/del_consume_type:
    delete:
      description: 删除种类列表
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: JSON数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/consume.DelConsumeTypeReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 消费管理相关接口
  /ledger/v1/consume/update_consume:
    put:
      description: 更新消费记录
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - description: JSON数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/consume.UpdateConsumeRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 消费管理相关接口
  /ledger/v1/user/captcha:
    get:
      description: 获取图片验证码
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 用户相关接口
  /ledger/v1/user/captcha_verify:
    post:
      description: 图片验证码校验
      parameters:
      - description: JSON数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.Verify'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 用户相关接口
  /ledger/v1/user/login:
    post:
      description: 用户登录
      parameters:
      - description: JSON数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 用户相关接口
  /ledger/v1/user/register:
    post:
      description: 用户注册
      parameters:
      - description: JSON数据
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.Register'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 用户相关接口
  /ledger/v1/user/send_activate:
    get:
      description: 发送激活码
      parameters:
      - in: query
        name: email
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 用户相关接口
  /ledger/v1/user/user_list:
    get:
      description: 用户列表
      parameters:
      - description: Bearer 31a165baebe6dec616b1f8f3207b4273
        in: header
        name: Authorization
        required: true
        type: string
      - in: query
        name: email
        type: string
      - in: query
        name: id
        type: integer
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      - in: query
        name: user_name
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webbase.Response'
      tags:
      - 用户相关接口
swagger: "2.0"
